[workspace]
resolver = "2"
members = [
    "./contracts/mock-oracle-contract",
    "./contracts/stability-pool-contract",
    "./contracts/trove-manager-contract",
    "./contracts/vesting-contract",
    "./contracts/sorted-troves-contract",
    "./contracts/borrow-operations-contract",
    "./contracts/token-contract",
]
