services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NETWORK=mainnet
    volumes:
      - ./.env:/app/.env
      - ./mainnet.contracts.json:/app/mainnet.contracts.json
      - ./testnet.contracts.json:/app/testnet.contracts.json
