[workspace]
members = [
  "./contracts/mock-oracle-contract",
  "./contracts/stability-pool-contract",
  "./contracts/trove-manager-contract",
  "./contracts/vesting-contract",
  "./contracts/sorted-troves-contract",
  "./contracts/borrow-operations-contract",
  "./contracts/active-pool-contract",
  "./contracts/token-contract",
  "./contracts/sorted-troves-contract/tests/artifacts",
]