[workspace]
members = [
  "./contracts/mock-oracle-contract",
  "./contracts/stability-pool-contract",
  "./contracts/trove-manager-contract",
  "./contracts/vesting-contract",
  "./contracts/sorted-troves-contract",
  "./contracts/borrow-operations-contract",
  "./contracts/protocol-manager-contract",
  "./contracts/active-pool-contract",
  "./contracts/default-pool-contract",
  "./contracts/coll-surplus-pool-contract",
  "./contracts/token-contract",
  "./contracts/usdf-token-contract",
  "./contracts/fpt-staking-contract",
  "./contracts/sorted-troves-contract/tests/artifacts",
  "./contracts/stability-pool-contract/tests/artifacts",
]