[package]
name = "mock-trove-manager-contract"
version = "0.1.0"
authors = ["hydrogen-labs"]
edition = "2021"
license = "Apache-2.0"

[dev-dependencies]
fuels = { workspace = true }
tokio = { workspace = true }


[[test]]
harness = true
name = "tests"
path = "tests/harness.rs"
