[project]
authors = ["hydrogen-labs"]
entry = "main.sw"
license = "Apache-2.0"
name = "trove-manager-contract"

[constants]
BETA = { type = "u64", value = "2" }
MINIMINUTE_DECAY_FACTORMUM_LIQUIDITY = { type = "u64", value = "999037758833783000" }
SECONDS_IN_ONE_MINUTE = { type = "u64", value = "60" }

[dependencies]
libraries = { path = "../../libraries" }
