[package]
name = "test-utils"
version = "0.0.0"
authors = ["Hydrogen-labs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = { version = "0.35.1", features = ["fuel-core-lib"] }

[lib]
doctest = false