[package]
name = "test-utils"
version = "0.0.0"
authors = ["Hydrogen-labs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
dotenv = "0.15.0"
fuels = { version = "0.49.0", features = ["fuel-core-lib"] }
futures = "0.3.17"
pbr = "1.1.1"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.92"
tokio = { version = "1.12", features = ["rt", "macros"] }

[lib]
doctest = false
