[package]
name = "test-utils"
version = "0.0.0"
authors = ["Hydrogen-labs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = { version = "0.38.1", features = ["fuel-core-lib"] }
futures = "0.3.17"
dotenv = "0.15.0"
pbr = "1.1.1"
tokio = { version = "1.12", features = ["rt", "macros"] }

[lib]
doctest = false