[project]
authors = ["hydrogen-labs"]
entry = "main.sw"
license = "Apache-2.0"
name = "mock-trove-manager-sp-contract"

[dependencies]
libraries = { path = "../../libraries" }

[proxy]
enabled = true
