name: CI

on:
  push:
    branches:
      - main

  release:
    types: [published]

env:
  RUST_VERSION: 1.68.1

jobs:
  lint-toml-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Install Cargo.toml linter
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-toml-lint
          version: "0.1"
      - name: Run Cargo.toml linter
        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Init cache
        uses: Swatinem/rust-cache@v1

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          toolchain: latest
          date: 2023-02-22

      # - name: Check Sway formatting
      #   run: |
      #     forc fmt --check
      # - name: Check Rust formatting
      #   run: |
      #     cargo fmt --verbose --check

      - name: Build Sway
        run: |
          forc build
      # Currently there's a weird bug on forc test that I cannot resolve
      # - name: Test Sway
      #   run: |
      #     forc test
      - name: Run Rust tests
        run: |
          cargo test
